version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host('${PORTAINER_SUBDOMAIN}.${DEFAULT_DOMAIN}')
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - ${TRAEFIK_NETWORK}
    environment:
      - PORTAINER_SUBDOMAIN=${PORTAINER_SUBDOMAIN}
      - DEFAULT_DOMAIN=${DEFAULT_DOMAIN}

networks:
  ${TRAEFIK_NETWORK}:
    external: true 